### ISSUE TITLE
redirect on login (fos user bundle feature)

### ISSUE THREAD

**Issue by Grummfy** [nucleos/NucleosProfileBundle#106]
## Feature Request

Hello,
In fos user bundle, once we are logged, we have some configuration to choose the way we are redirected.

I think it could be nice to have some change, and hooking it inside \Nucleos\ProfileBundle\EventListener\AlreadyLoggedinListener to use this configuration, or by default continue with the actual code.

thanks

**Comment by core23** [comment]
This is already possible. You can use the event system for this.

https://github.com/nucleos/NucleosUserBundle/blob/main/src/NucleosUserEvents.php#L167-L175

**Comment by Grummfy** [comment]
well, you go to your final class AlreadyLoggedinListener so, because, as far as I know, there is no priority in the event system of Symfony, there is no guaranty for that.

For now, the only way to be sure of this, is to force the service declaration of another listener that will repalce the service id of AlreadyLoggedinListener (and because it's final, to duplicate the code, except the interesting part)

**Comment by core23** [comment]
Should be fixed with the latest 1.12.0 release: https://github.com/nucleos/NucleosUserBundle/pull/453
