### ISSUE TITLE
Overriding registration form

### ISSUE THREAD

**Issue by Bartololo12** [nucleos/NucleosProfileBundle#142]
## Is it possible to override registration form?

I need to have users to accept the terms during registration. This doesn't come with default registration form. Is it possible to override the form?

**Comment by core23** [comment]
Yes this is possible. There are some (WIP) docs: https://docs.nucleos.rocks/projects/profile-bundle/en/latest/customize_registration.html

**Comment by Bartololo12** [comment]
Thank you @core23 for fast response. I am struggling at the moment to find out more about symfony FormExtensions I can only see Form type extensions, but I will try to investigate more.

**Comment by Bartololo12** [comment]
For anyone else looking for that. You need to extend `AbstractTypeExtension` and implement method `getExtendedTypes`. For registration form it will be:

```php
public static function getExtendedTypes(): iterable
{
    return ['Nucleos\ProfileBundle\Form\Type\RegistrationFormType'];
}
```

**Comment by core23** [comment]
Thanks for suggestion. Can you add some notes to the docs. This would help a lot.
