### ISSUE TITLE
Disabled user can login

### ISSUE THREAD

**Issue by Zisteron** [nucleos/NucleosProfileBundle#180]
#### Packages

`composer/package-versions-deprecated 1.11.99.1 1.11.99.1 Composer plugin that provides efficient querying for installed package versions (no runtime IO)
doctrine/annotations                 1.11.1    1.11.1    Docblock Annotations Parser
doctrine/cache                       1.10.2    1.10.2    PHP Doctrine Cache library is a popular cache implementation that supports many different drivers such as redis, memcache, apc, mongodb and others.
doctrine/collections                 1.6.7     1.6.7     PHP Doctrine Collections library that adds additional functionality on top of PHP arrays.
doctrine/common                      3.1.0     3.1.0     PHP Doctrine Common project is a library that provides additional functionality that other Doctrine projects depend on such as better reflection support, proxies and much more.
doctrine/dbal                        2.12.1    3.0.0     Powerful PHP database abstraction layer (DBAL) with many features for database schema introspection and management.
doctrine/doctrine-bundle             2.2.2     2.2.2     Symfony DoctrineBundle
doctrine/doctrine-migrations-bundle  3.0.2     3.0.2     Symfony DoctrineMigrationsBundle
doctrine/event-manager               1.1.1     1.1.1     The Doctrine Event Manager is a simple PHP event system that was built to be used with the various Doctrine projects.
doctrine/inflector                   2.0.3     2.0.3     PHP Doctrine Inflector is a small library that can perform string manipulations with regard to upper/lowercase and singular/plural forms of words.
doctrine/instantiator                1.4.0     1.4.0     A small, lightweight utility to instantiate objects in PHP without invoking their constructors
doctrine/lexer                       1.2.1     1.2.1     PHP Doctrine Lexer parser library that can be used in Top-Down, Recursive Descent Parsers.
doctrine/migrations                  3.0.2     3.0.2     PHP Doctrine Migrations project offer additional functionality on top of the database abstraction layer (DBAL) for versioning your database schema and easily deploying changes to it. It is a very easy to ...
doctrine/orm                         2.8.1     2.8.1     Object-Relational-Mapper for PHP
doctrine/persistence                 2.1.0     2.1.0     The Doctrine Persistence project is a set of shared interfaces and functionality that the different Doctrine object mappers share.
doctrine/sql-formatter               1.1.1     1.1.1     a PHP SQL highlighting library
easycorp/easyadmin-bundle            v3.2.1    v3.2.1    Admin generator for Symfony applications
egulias/email-validator              2.1.25    3.0.0     A library for validating emails against several RFCs
friendsofphp/proxy-manager-lts       v1.0.3    v1.0.3    Adding support for a wider range of PHP versions to ocramius/proxy-manager
jms/metadata                         2.4.0     2.4.0     Class/method/property metadata management in PHP
laminas/laminas-code                 3.4.1     3.5.1     Extensions to the PHP Reflection API, static code scanning, and code generation
laminas/laminas-eventmanager         3.3.0     3.3.0     Trigger and listen to events within a PHP application
laminas/laminas-zendframework-bridge 1.1.1     1.1.1     Alias legacy ZF class names to Laminas Project equivalents.
monolog/monolog                      1.26.0    2.2.0     Sends your logs to files, sockets, inboxes, databases and various web services
nikic/php-parser                     v4.10.4   v4.10.4   A PHP parser written in PHP
nucleos/profile-bundle               1.3.0     1.3.0     Registration and profile management for symfony
nucleos/user-bundle                  1.7.0     1.7.0     Lightweight user management for symfony
phpdocumentor/reflection-common      2.2.0     2.2.0     Common reflection classes used by phpdocumentor to reflect the code structure
phpdocumentor/reflection-docblock    5.2.2     5.2.2     With this component, a library can provide support for annotations via DocBlocks or otherwise retrieve information that is embedded in a DocBlock.
phpdocumentor/type-resolver          1.4.0     1.4.0     A PSR-5 based resolver of Class names, Types and Structural Element Names
psr/cache                            1.0.1     1.0.1     Common interface for caching libraries
psr/container                        1.0.0     1.0.0     Common Container Interface (PHP FIG PSR-11)
psr/link                             1.0.0     1.0.0     Common interfaces for HTTP links
psr/log                              1.1.3     1.1.3     Common interface for logging libraries
sensio/framework-extra-bundle        v5.6.1    v5.6.1    This bundle provides a way to configure your controllers with annotations
symfony/apache-pack                  v1.0.1    v1.0.1    A pack for Apache support in Symfony
symfony/asset                        v4.4.18   v5.2.1    Symfony Asset Component
symfony/browser-kit                  v4.4.18   v5.2.1    Symfony BrowserKit Component
symfony/cache                        v4.4.18   v5.2.1    Symfony Cache component with PSR-6, PSR-16, and tags
symfony/cache-contracts              v2.2.0    v2.2.0    Generic abstractions related to caching
symfony/config                       v4.4.18   v5.2.1    Symfony Config Component
symfony/console                      v4.4.18   v5.2.1    Symfony Console Component
symfony/css-selector                 v4.4.18   v5.2.1    Symfony CssSelector Component
symfony/debug                        v4.4.18   v4.4.18   Symfony Debug Component
symfony/debug-bundle                 v4.4.18   v5.2.1    Symfony DebugBundle
symfony/dependency-injection         v4.4.18   v5.2.1    Symfony DependencyInjection Component
symfony/deprecation-contracts        v2.2.0    v2.2.0    A generic function and convention to trigger deprecation notices
symfony/doctrine-bridge              v4.4.18   v5.2.1    Symfony Doctrine Bridge
symfony/dom-crawler                  v4.4.18   v5.2.1    Symfony DomCrawler Component
symfony/dotenv                       v4.4.18   v5.2.1    Registers environment variables from a .env file
symfony/error-handler                v4.4.18   v5.2.1    Symfony ErrorHandler Component
symfony/event-dispatcher             v4.4.18   v5.2.1    Symfony EventDispatcher Component
symfony/event-dispatcher-contracts   v1.1.9    v2.2.0    Generic abstractions related to dispatching event
symfony/expression-language          v4.4.18   v5.2.1    Symfony ExpressionLanguage Component
symfony/filesystem                   v4.4.18   v5.2.1    Symfony Filesystem Component
symfony/finder                       v4.4.18   v5.2.1    Symfony Finder Component
symfony/flex                         v1.11.0   v1.11.0   Composer plugin for Symfony
symfony/form                         v4.4.18   v5.2.1    Symfony Form Component
symfony/framework-bundle             v4.4.18   v5.2.1    Symfony FrameworkBundle
symfony/http-client                  v4.4.18   v5.2.1    Symfony HttpClient component
symfony/http-client-contracts        v2.3.1    v2.3.1    Generic abstractions related to HTTP clients
symfony/http-foundation              v4.4.18   v5.2.1    Symfony HttpFoundation Component
symfony/http-kernel                  v4.4.18   v5.2.1    Symfony HttpKernel Component
symfony/inflector                    v4.4.18   v5.2.1    Symfony Inflector Component
symfony/intl                         v4.4.18   v5.2.1    A PHP replacement layer for the C intl extension that includes additional data from the ICU library.
symfony/mailer                       v4.4.18   v5.2.1    Symfony Mailer Component
symfony/maker-bundle                 v1.28.0   v1.28.0   Symfony Maker helps you create empty commands, controllers, form classes, tests and more so you can forget about writing boilerplate code.
symfony/mercure                      v0.4.1    v0.4.1    Symfony Mercure Component
symfony/mercure-bundle               v0.2.6    v0.2.6    Symfony MercureBundle
symfony/mime                         v4.4.18   v5.2.1    A library to manipulate MIME messages
symfony/monolog-bridge               v4.4.18   v5.2.1    Symfony Monolog Bridge
symfony/monolog-bundle               v3.6.0    v3.6.0    Symfony MonologBundle
symfony/options-resolver             v4.4.18   v5.2.1    Symfony OptionsResolver Component
symfony/phpunit-bridge               v5.2.1    v5.2.1    Symfony PHPUnit Bridge
symfony/polyfill-intl-grapheme       v1.22.0   v1.22.0   Symfony polyfill for intl's grapheme_* functions
symfony/polyfill-intl-icu            v1.22.0   v1.22.0   Symfony polyfill for intl's ICU-related data and classes
symfony/polyfill-intl-idn            v1.22.0   v1.22.0   Symfony polyfill for intl's idn_to_ascii and idn_to_utf8 functions
symfony/polyfill-intl-normalizer     v1.22.0   v1.22.0   Symfony polyfill for intl's Normalizer class and related functions
symfony/polyfill-mbstring            v1.22.0   v1.22.0   Symfony polyfill for the Mbstring extension
symfony/polyfill-php72               v1.22.0   v1.22.0   Symfony polyfill backporting some PHP 7.2+ features to lower PHP versions
symfony/polyfill-php73               v1.22.0   v1.22.0   Symfony polyfill backporting some PHP 7.3+ features to lower PHP versions
symfony/polyfill-php80               v1.22.0   v1.22.0   Symfony polyfill backporting some PHP 8.0+ features to lower PHP versions
symfony/polyfill-uuid                v1.22.0   v1.22.0   Symfony polyfill for uuid functions
symfony/process                      v4.4.18   v5.2.1    Symfony Process Component
symfony/property-access              v4.4.18   v5.2.1    Symfony PropertyAccess Component
symfony/property-info                v4.4.18   v5.2.1    Symfony Property Info Component
symfony/proxy-manager-bridge         v4.4.18   v5.2.1    Symfony ProxyManager Bridge
symfony/routing                      v4.4.18   v5.2.1    Symfony Routing Component
symfony/security-bundle              v4.4.18   v5.2.1    Symfony SecurityBundle
symfony/security-core                v4.4.18   v5.2.1    Symfony Security Component - Core Library
symfony/security-csrf                v4.4.18   v5.2.1    Symfony Security Component - CSRF Library
symfony/security-guard               v4.4.18   v5.2.1    Symfony Security Component - Guard
symfony/security-http                v4.4.18   v5.2.1    Symfony Security Component - HTTP Integration
symfony/serializer                   v4.4.18   v5.2.1    Symfony Serializer Component
symfony/service-contracts            v2.2.0    v2.2.0    Generic abstractions related to writing services
symfony/stopwatch                    v4.4.18   v5.2.1    Symfony Stopwatch Component
symfony/string                       v5.2.1    v5.2.1    Symfony String component
symfony/translation                  v4.4.18   v5.2.1    Symfony Translation Component
symfony/translation-contracts        v2.3.0    v2.3.0    Generic abstractions related to translation
symfony/twig-bridge                  v4.4.18   v5.2.1    Symfony Twig Bridge
symfony/twig-bundle                  v4.4.18   v5.2.1    Symfony TwigBundle
symfony/uid                          v5.2.1    v5.2.1    Symfony Uid component
symfony/validator                    v4.4.18   v5.2.1    Symfony Validator Component
symfony/var-dumper                   v4.4.18   v5.2.1    Symfony mechanism for exploring and dumping PHP variables
symfony/var-exporter                 v4.4.18   v5.2.1    A blend of var_export() + serialize() to turn any serializable data structure to plain PHP code
symfony/web-link                     v4.4.18   v5.2.1    Symfony WebLink Component
symfony/web-profiler-bundle          v4.4.18   v5.2.1    Symfony WebProfilerBundle
symfony/yaml                         v4.4.18   v5.2.1    Symfony Yaml Component
twig/extra-bundle                    v3.2.1    v3.2.1    A Symfony bundle for extra Twig extensions
twig/twig                            v3.2.1    v3.2.1    Twig, the flexible, fast, and secure template language for PHP
vich/uploader-bundle                 1.16.0    1.16.0    Ease file uploads attached to entities
webmozart/assert                     1.9.1     1.9.1     Assertions to validate method input/output with nice error messages.`

#### PHP version
7.4

## Subject
1) user can login if have enabled 0
2) confirmation link from email show error and user is not activated

## Expected results
1) user receive error that is disabled
2) user will be activated and logged in

## Actual results
1) use can login without any error
2) after click confirmation link this error show:
Argument 3 passed to Nucleos\ProfileBundle\Action\ConfirmRegistrationAction::__construct() must implement interface Symfony\Component\Routing\RouterInterface, instance of Twig\Environment given, called in

**Comment by core23** [comment]
>     2\. after click confirmation link this error show:
>         Argument 3 passed to Nucleos\ProfileBundle\Action\ConfirmRegistrationAction::__construct() must implement interface Symfony\Component\Routing\RouterInterface, instance of Twig\Environment given, called in

https://github.com/nucleos/NucleosProfileBundle/pull/172 fixes the bug

Can you provide a PR with a fix so that a disabled user can't login @Zisteron

**Comment by core23** [comment]
Fixed with https://github.com/nucleos/NucleosUserBundle/pull/273
