### ISSUE TITLE
ResettingMail used instead of RegistrationMail

### ISSUE THREAD

**Issue by lgeorget** [nucleos/NucleosProfileBundle#240]
Hello!

During my tests, I noticed that the registration workflow uses the ResettingMail class from the NucleosUserBundle instead of the RegistrationMail defined in the NucleosProfileBundle (see https://github.com/nucleos/NucleosProfileBundle/blob/1566c28d5292c02e21057f1e065661015972a0bb/src/Mailer/Mailer.php#L67).
Is there any good reason for this that I might have overlooked?

**Comment by core23** [comment]
You you provide a PR with a fix @lgeorget ?

**Comment by lgeorget** [comment]
Sure enough :-) here you go: https://github.com/nucleos/NucleosProfileBundle/pull/241
