### ISSUE TITLE
resolve deprecation

### ISSUE THREAD

**Issue by Slash663** [nucleos/NucleosProfileBundle#480]
Hello,

Could you please correct this : 

User Deprecated: Since symfony/security-core 5.2: Method "Symfony\Component\Security\Core\Authentication\Token\UsernamePasswordToken::getProviderKey" is deprecated, use "getFirewallName()" instead.

in file

/nucleos/profile-bundle/src/Action/RegistrationConfirmedAction.php:**65**

Thank you

**Comment by core23** [comment]
Can you provide a PR to remove the deprecations @Slash663

**Comment by Slash663** [comment]
I hope I did it correctly this time :)
