### ISSUE TITLE
User should be enabled automatically when registration confirmation is disabled

### ISSUE THREAD

**Issue by alexsegura** [nucleos/NucleosProfileBundle#511]
When you have `nucleos_profile.registration.confirmation.enabled = false`, and you have a `Nucleos\UserBundle\Security\UserChecker` configured in `security.yaml` (as recommended in documentation), it's actually impossible to register/login, because the user gets stored in database with `enabled = false`, and can't login. 

In this case, it makes sense the the user is automatically enabled after registration.

**Comment by core23** [comment]
Can you provide a PR @alexsegura ?

**Comment by alexsegura** [comment]
I think yes. I'm currently looking at the best way to do it, probably via a listener with `REGISTRATION_INITIALIZE` or `REGISTRATION_SUCCESS`.

**Comment by core23** [comment]
After thinking a little bit more about it, it could be intended that the account is disabled.

For example a user could register itself but some admin must confirm the account.
